version: 2
updates:
  # Python dependencies for Flask
  - package-ecosystem: "pip"
    directory: "/flask"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@mat"
    commit-message:
      prefix: "flask"
      include: "scope"

  # Python dependencies for FastAPI  
  - package-ecosystem: "pip"
    directory: "/fastapi"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@mat"
    commit-message:
      prefix: "fastapi"
      include: "scope"

  # Go dependencies
  - package-ecosystem: "gomod"
    directory: "/go"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@mat"
    commit-message:
      prefix: "go"
      include: "scope"

  # Elixir dependencies
  - package-ecosystem: "mix"
    directory: "/elixir"
    schedule:
      interval: "weekly" 
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@mat"
    commit-message:
      prefix: "elixir"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@mat"
    commit-message:
      prefix: "ci"
      include: "scope"